### ISSUE TITLE
Docs update request: /node-running/node-providers

### ISSUE THREAD

**Issue by nebojsa-ristovic** [OffchainLabs/arbitrum-docs#1023]
Source: https://docs.arbitrum.io/node-running/node-providers

Request: Please add Tenderly (https://tenderly.co/) as a Third-party RPC provider for all Arbitrum networks with WSS support.

```[tasklist]
### Tasks
```

**Comment by anegg0** [comment]
Hi @nebojsa-ristovic, and apologies for seeing this so late!
We're happy to add Tenderly to the node providers list.
Could you share a reference IRL to add to the [node providers list](https://docs.arbitrum.io/build-decentralized-apps/reference/node-providers#third-party-rpc-providers)?

**Comment by anegg0** [comment]
Closing this issue as there was no follow-up to this conversation.

**Comment by nebojsa-ristovic** [comment]
> Closing this issue as there was no follow-up to this conversation.

Hey, now I am late, I missed your previous message somehow. 
Here are the references:
https://docs.tenderly.co/node
https://docs.tenderly.co/node/rpc-reference

You'll see Tenderly supports all 3 Arbitrum networks, and has Websocket support as well.
