### ISSUE TITLE
Docs update request: /node-running/node-providers

### ISSUE THREAD

**Issue by maradeeym** [OffchainLabs/arbitrum-docs#1061]
Source: https://docs.arbitrum.io/node-running/node-providers

DRPC changed its branding to dRPC. See here: https://drpc.org/

dRPC also supports [ARB Sepolia](https://arbitrum-sepolia.drpc.org).

**Comment by anegg0** [comment]
This issue is handled in this [pending PR](https://github.com/OffchainLabs/arbitrum-docs/pull/1692).
