### ISSUE TITLE
Docs update request: /devs-how-tos/how-to-estimate-gas

### ISSUE THREAD

**Issue by firnprotocol** [OffchainLabs/arbitrum-docs#1080]
Source: https://docs.arbitrum.io/devs-how-tos/how-to-estimate-gas

Request: (how can we help?)

Psst, this issue will be closed with a templated response if it isn't a documentation update request.

what, if anything, should we do to calculate fees now that Dencun has dropped?

do we need to change how we submit transactions to arbitrum, or no?

what client-side migrations, if any, are needed?

thanks in advance.

**Comment by TucksonDev** [comment]
Hey, issues opened in this repository should only address the dev documentation portal. Questions like yours are better addressed in our Discord server.
I'll make an exception here to answer your question: no changes are needed to estimate gas fees after the Dencun upgrade. If you need more information, feel free to send us a message on Discord.
