### ISSUE TITLE
Docs update request: /stylus/reference/testnet-information

### ISSUE THREAD

**Issue by haardikk21** [OffchainLabs/arbitrum-docs#1096]
Source: https://docs.arbitrum.io/stylus/reference/testnet-information

Request: 

- Add LearnWeb3 Arbitrum Sepolia Faucet to the docs (https://learnweb3.io/faucets/arbitrum_sepolia)

**Comment by anegg0** [comment]
Hi, @haardikk21, 
We'll happily include your content once our portal validates your project. To do that, please submit your project to [Arbitrum portal](https://portal.arbitrum.io/) by filling out [this form](https://forms.gle/Vzzz39VLakHJ57ib7)), then open a PR with your content suggestions.

**Comment by pete-vielhaber** [comment]
Stylus testnet is deprecated and adding this contribution would no longer have benefit. Thank you for your contribution!
