### ISSUE TITLE
Docs update request: /devs-how-tos/how-to-estimate-gas

### ISSUE THREAD

**Issue by 0xSaga** [OffchainLabs/arbitrum-docs#1102]
Source: https://docs.arbitrum.io/devs-how-tos/how-to-estimate-gas

Request: Update gas estimate instructions after EIP-4844.

**Comment by TucksonDev** [comment]
Hello!
The way to estimate gas on Arbitrum hasn't changed with the new upgrade, so that information is still valid.
Thanks!
