### ISSUE TITLE
fix darkmode landing page on load CSS issue

### ISSUE THREAD

**Issue by DZGoldman** [OffchainLabs/arbitrum-docs#12]
Switch to darkmode & reload, CSS breaks; not (trivially) reproducible locally

**Comment by fionnachan** [comment]
need to wait for a fix for https://github.com/facebook/docusaurus/issues/7986

**Comment by fionnachan** [comment]
reproducible locally by running `yarn build` then `yarn serve`

**Comment by DZGoldman** [comment]
humbug (ty for the find & repro tho @fionnachan )

**Comment by fionnachan** [comment]
fixed with new design
