### ISSUE TITLE
Docs update request: /how-arbitrum-works/inside-arbitrum-nitro

### ISSUE THREAD

**Issue by OrfeasLitos** [OffchainLabs/arbitrum-docs#1293]
Source: https://docs.arbitrum.io/how-arbitrum-works/inside-arbitrum-nitro

Request:

In "Arbitrum Rollup Protocol" -> "Staking", change the sentence "Notice that once you are staked on an RBlock, there is no way to unstake." to "Notice that once you are staked on an _unresolved_ RBlock, there is no way to unstake."

**Comment by pete-vielhaber** [comment]
Addressing in [PR 1863](https://github.com/OffchainLabs/arbitrum-docs/pull/1863)
