### ISSUE TITLE
error when running nitro's make command

### ISSUE THREAD

**Issue by fahimahmedx** [OffchainLabs/arbitrum-docs#1298]
I get the following error when running the make command for the nitro repository. It's saying that forge needs to be installed, so the docs should be updated to include the step for installing forge if not already installed on a fresh setup.

> Compiled 149 Solidity files successfully (evm target: london).
✨  Done in 32.73s.
yarn --cwd contracts build:forge:yul
yarn run v1.22.22
warning package.json: License should be a valid SPDX license expression
$ FOUNDRY_PROFILE=yul forge build --skip *.sol
/bin/sh: forge: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [.make/solidity] Error 127

**Comment by joshuacolvin0** [comment]
This has already been handled
