### ISSUE TITLE
Docs update request: /stylus/stylus-quickstart

### ISSUE THREAD

**Issue by Julsss1726** [OffchainLabs/arbitrum-docs#1420]
Source: https://docs.arbitrum.io/stylus/stylus-quickstart

Request: (how can we help?)

Psst, this issue will be closed with a templated response if it isn't a documentation update request.
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [ ] https://github.com/OffchainLabs/arbitrum-docs/pull/1401
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/1419
```

**Comment by anegg0** [comment]
The content has been updated. Thank you for reaching out, @Julsss1726!
