### ISSUE TITLE
Docs update request: /stylus/stylus-gentle-introduction

### ISSUE THREAD

**Issue by ABITCOINGOLD** [OffchainLabs/arbitrum-docs#1426]
HERE IS OUR ABG SMART CONTRACT ADDRESS  OF ABBITRUM ONE  This is bridge token
https://arbiscan.io/token/0x8740c7B2a01834a9DEf858856B352B7E3aAEcF25#balances)

**Comment by anegg0** [comment]
Hi @ABITCOINGOLD, could you clarify what modification you would like to see?
