### ISSUE TITLE
Docs update request: /build-decentralized-apps/reference/node-providers

### ISSUE THREAD

**Issue by dan-kazenoff-vcc** [OffchainLabs/arbitrum-docs#1430]
Source: https://docs.arbitrum.io/build-decentralized-apps/reference/node-providers

Request: Validation Cloud (https://validationcloud.io) Supports Arbitrum:

- Arb One Mainnet is supported
- Websocket is supported 

We have a no-credit card free tier for up to 50 million compute units. Beyond that, a scale plan is required.

**Comment by anegg0** [comment]
Hi, @dan-kazenoff-vcc, 
We'll happily include your content once our portal validates your project. To do that, please submit your project to [Arbitrum portal](https://portal.arbitrum.io/) by filling out [this form](https://forms.gle/Vzzz39VLakHJ57ib7)), then open a PR with your content suggestions.
