### ISSUE TITLE
stylus docs: bwarelabs link goes to a 404

### ISSUE THREAD

**Issue by hooperben** [OffchainLabs/arbitrum-docs#1437]
<img width="705" alt="image" src="https://github.com/user-attachments/assets/d767a76a-2a48-402f-9c75-1d18626f50f8">

<img width="825" alt="image" src="https://github.com/user-attachments/assets/54f2a500-5096-45ac-a8d8-8e98287a3af2">

not sure what best practise is, but changing to public PRs with branch protection on important branches might be a good idea too ;)

<img width="995" alt="image" src="https://github.com/user-attachments/assets/c1d8af03-f387-4dc2-94ba-923603a702be">

**Comment by anegg0** [comment]
Thank you for your suggestions and for kindly specifying the issue and its solution, @hooperben.
The fix has been merged.
