### ISSUE TITLE
Docs update request: /run-arbitrum-node/data-availability-committees/configure-dac

### ISSUE THREAD

**Issue by SatpalSandhu61** [OffchainLabs/arbitrum-docs#1439]
Source: https://docs.arbitrum.io/run-arbitrum-node/data-availability-committees/configure-dac

Request: When will the "Configure DAC" documentation be available? Currently the page just displays:

"UNDER CONSTRUCTION
This document is currently under construction.

If you're waiting for this content to be completed, click the Request an update button at the top of this page to let us know. We incorporate these requests into our content prioritization discussions. Thank you!"

**Comment by anegg0** [comment]
Hi @SatpalSandhu61, and thank you for taking the time to send us your feedback.
We will remove the placeholder article you mentioned.
You can find info on DAC configuration in [this article, which explains how to set up an AnyTrust Orbit chain](https://docs.arbitrum.io/launch-orbit-chain/how-tos/orbit-sdk-deploying-anytrust-chain#4-setting-valid-keyset-on-parent-chain).
Let us know what you think!
