### ISSUE TITLE
Docs update request: /inside-arbitrum-nitro/

### ISSUE THREAD

**Issue by mehong07** [OffchainLabs/arbitrum-docs#148]
Source: https://developer.arbitrum.io/inside-arbitrum-nitro/

Request: (how can we help?)
![Screenshot_2023-03-16-22-32-27-290_com bitkeep wallet](https://user-images.githubusercontent.com/116629213/225650050-e8ef2031-e616-4f98-900f-1bff2d1c8b0a.jpg)
![Screenshot_2023-03-16-22-30-34-192_com android chrome](https://user-images.githubusercontent.com/116629213/225650071-f1e1f4b7-e8fc-4112-b9b3-17aa2ade995e.jpg)

why am I not eligible even though I have lots of transactions

**Comment by mehong07** [comment]
![Screenshot_2023-03-16-22-34-45-309_com bitkeep wallet](https://user-images.githubusercontent.com/116629213/225650669-a3fb9729-2f44-4524-bcae-91c6b9653ce2.jpg)
I even had transactions at Arbk, please check again
Adress 0xF7962D47939FF7F9ef368C2787952fe73F47E78a

**Comment by DZGoldman** [comment]
Hi there - this is a templated response used to close docs repo issues that aren't related to content. Visit the [Arbitrum Discord](https://discord.com/invite/arbitrum) and/or [Arbitrum Telegram](https://t.me/arbitrum) if you haven't already - you'll find a variety of support and discussion channels there. Thank you :orange_heart::blue_heart:
