### ISSUE TITLE
Docs update request: /how-arbitrum-works/inside-arbitrum-nitro

### ISSUE THREAD

**Issue by adminseedlatam** [OffchainLabs/arbitrum-docs#1489]
Source: https://docs.arbitrum.io/how-arbitrum-works/inside-arbitrum-nitro

Request: Change the draw of how Arbitrum chain work

Replace with this diagram:

![ArbitrumChainDiagram](https://github.com/user-attachments/assets/67bf7ad9-c375-4f21-80dd-c2cdb3c24b24)

**Comment by anegg0** [comment]
Thank you for your contribution,  @adminseedlatam !
Will merge shortly.

**Comment by anegg0** [comment]
@adminseedlatam, would you mind sharing the code of your diagram?

**Comment by anegg0** [comment]
@adminseedlatam, we owe an update: 
The napkin sketch has sentimental value to our team, as it was made in the ideation phase of Arbitrum by one of our founders. We decided to keep it, but we want to thank you once again for your contribution :)
