### ISSUE TITLE
Stylus precompiles are hard to use

### ISSUE THREAD

**Issue by leeederek** [OffchainLabs/arbitrum-docs#1503]
pain points:
- stylus precompiles are hard to find (you have to go here: https://docs.arbitrum.io/stylus/reference/testnet-information#precompiles when i expected a separate precompile tab on the left hand side)
- all the precompile links are broken 
- there's no way to see the methods for each precompile easily. I expect the experience to be like: https://docs.arbitrum.io/build-decentralized-apps/precompiles/reference

**Comment by anegg0** [comment]
Noted, on it, thanks for flagging this, @leeederek
