### ISSUE TITLE
update audit reports in our docs

### ISSUE THREAD

**Issue by leeederek** [OffchainLabs/arbitrum-docs#1504]
Add the following audit reports to this page: https://docs.arbitrum.io/audit-reports

- https://github.com/trailofbits/publications/blob/master/reviews/2024-04-offchain-arbos-30-nitro-upgrade-securityreview.pdf
- https://github.com/trailofbits/publications/blob/master/reviews/2024-04-offchain-arbos-31-securityreview.pdf
- https://github.com/trailofbits/publications/blob/master/reviews/2024-04-offchain-l1-l3-teleporter-securityreview.pdf
- https://www.chainsecurity.com/security-audit/offchain-labs-fund-distribution

**Comment by anegg0** [comment]
On it. PR to follow in the next hour.

**Comment by anegg0** [comment]
Issue addressed in this [PR](https://github.com/OffchainLabs/arbitrum-docs/pull/1505)
