### ISSUE TITLE
Docs update request: /launch-orbit-chain/how-tos/customize-deployment-configuration

### ISSUE THREAD

**Issue by RexShinka** [OffchainLabs/arbitrum-docs#1506]
Source: https://docs.arbitrum.io/launch-orbit-chain/how-tos/customize-deployment-configuration

Request: (how can we help?)

ChainID
Don't worry about this; it's inconsequential for devnets. In production scenarios (which aren't yet supported), 

Since production scenarios are now being deployed, this text should reflect that.

Psst, this issue will be closed with a templated response if it isn't a documentation update request.

**Comment by anegg0** [comment]
Duly noted. Thank you for flagging this, @RexShinka!

**Comment by pete-vielhaber** [comment]
Will be addressed in [PR 1863](https://github.com/OffchainLabs/arbitrum-docs/pull/1863)
