### ISSUE TITLE
Docs update request: /build-decentralized-apps/reference/node-providers

### ISSUE THREAD

**Issue by maradeeym** [OffchainLabs/arbitrum-docs#1522]
Source: https://docs.arbitrum.io/build-decentralized-apps/reference/node-providers

Request: (how can we help?)

Few updates to the table of node providers:

1. DRPC is now written dPRC.
2. dRPC also supports [Sepolia](https://drpc.org/chainlist/arbitrum#arbitrum-sepolia)
3. New URL is: https://drpc.org/chainlist/arbitrum

Psst, this issue will be closed with a templated response if it isn't a documentation update request.

**Comment by anegg0** [comment]
Noted, @maradeeym, will update shortly.
