### ISSUE TITLE
server-side redirect for old / not-found routes

### ISSUE THREAD

**Issue by DZGoldman** [OffchainLabs/arbitrum-docs#16]
Currently we do this hacky client-side thing, gives a weird flicker https://github.com/OffchainLabs/nitro-docs/blob/b07b7f06aed3221a65458961d33fa0949c815e8d/website/src/pages/index.js#L11

**Comment by gzeoneth** [comment]
lol I still remember I did this https://github.com/OffchainLabs/developer-website/pull/59/files

**Comment by TucksonDev** [comment]
Redirections are now handled by Vercel
