### ISSUE TITLE
Docs update request: /node-running/node-providers

### ISSUE THREAD

**Issue by JoGetBlock** [OffchainLabs/arbitrum-docs#162]
Source: https://developer.arbitrum.io/node-running/node-providers

Request: please update that that GetBlock supports Arbitrum Nova (on dedicated nodes) and today we add Goerly to our support too

**Comment by DZGoldman** [comment]
hi @JoGetBlock! Can you point me to where on the GetBlock site I would go to connect to Nova? I currently only see mentions of 2 networks [here](https://getblock.io/dedicated-nodes/arbitrum/), "mainnet" and "testnet"

**Comment by DZGoldman** [comment]
Closing for now; if the docs get updated you can let us know via the [form](https://docs.google.com/forms/u/1/d/e/1FAIpQLSdw0U-9LcLuih5TZ_QghS-S_MS4wCKSEigA_IQEza_hFmNVow/viewform), thanks!
