### ISSUE TITLE
Docs update request: /how-arbitrum-works/inside-arbitrum-nitro

### ISSUE THREAD

**Issue by Ritik-Agarwal50** [OffchainLabs/arbitrum-docs#1622]
Source: https://docs.arbitrum.io/how-arbitrum-works/inside-arbitrum-nitro
While reading the docs I found this small grammatical mistake.
At this line - https://github.com/OffchainLabs/arbitrum-docs/blob/e2a489de636f01993904e4128f4293c8beb2e08c/arbitrum-docs/how-arbitrum-works/inside-arbitrum-nitro.md?plain=1#L388
there is a repetition of `that` word 

![Screenshot 2024-09-02 112540](https://github.com/user-attachments/assets/11d2cbae-e31c-4901-b22d-2880558afd9c)

**Comment by anegg0** [comment]
Thank you for raising the issue, @Ritik-Agarwal50. This is not a typo: it could have been said this way:
"..., and that this execution will consume M inbox messages and transform the hash of outputs from H’ to H."
