### ISSUE TITLE
Docs update request: /stylus-by-example/hello_world

### ISSUE THREAD

**Issue by 0xNeshi** [OffchainLabs/arbitrum-docs#1672]
Source: https://docs.arbitrum.io/stylus-by-example/hello_world

Request: The example `Cargo.toml` is missing the `debug` flag, but the docs state that it should be there: `...and set the debug feature flag as shown in line 7 of the Cargo.toml file below.`.

**Comment by pete-vielhaber** [comment]
Looks like this was addressed in this [PR](https://github.com/OffchainLabs/stylus-by-example/pull/48)
