### ISSUE TITLE
Docs update request: /launch-orbit-chain/how-tos/fast-withdrawals

### ISSUE THREAD

**Issue by gmehta2** [OffchainLabs/arbitrum-docs#1801]
Source: https://docs.arbitrum.io/launch-orbit-chain/how-tos/fast-withdrawals

Request: At the very bottom of this page put a notice: 

Immediately after configuring fast withdrawals - your chain may not be operating fully at speed yet. This is because the validators have to work through the backlog of assertions which were not yet confirmed. You will see a series of `NodeCreated` and `NodeConfirmed` events. Once the backlog has been processed, your chain should operate fully at speed.

**Comment by pete-vielhaber** [comment]
Added note, thank you!
