### ISSUE TITLE
Docs update request: /stylus/troubleshooting-building-stylus

### ISSUE THREAD

**Issue by rimrakhimov** [OffchainLabs/arbitrum-docs#1840]
Source: https://docs.arbitrum.io/stylus/troubleshooting-building-stylus#how-is-a-stylus-contract-deployed

Request: the magic prefix specified should probably be not `0xEF000000` but `0xEFF00000` (e.g., stylus contract on arbitrum sepolia - https://arbitrum-sepolia.blockscout.com/address/0x230E6Ba137cB4C34624044a83485a99206FD29e6?tab=contract)

**Comment by pete-vielhaber** [comment]
Verified magic prefix is incorrect, will make update. Thank you!
