### ISSUE TITLE
Goerli Ethereum no longer used. We need enrolling validators onchain (via ELX faucet) for testnet v3. Wen Sepolia?

### ISSUE THREAD

**Issue by atimark** [OffchainLabs/arbitrum-docs#1924]
Goerli Ethereum no longer used. We need enrolling validators onchain (via ELX faucet) for testnet v3. Wen Sepolia?

_Originally posted by @shipper96 in https://github.com/trailofbits/publications/issues/353_

**Comment by Stas076** [comment]
README.md
