### ISSUE TITLE
0x2662550a2b3859385d97399e06237e40a2513E29

### ISSUE THREAD

**Issue by kaasipa** [OffchainLabs/arbitrum-docs#193]
Source: https://developer.arbitrum.io/getting-started-devs

Request: (how can we help?)

Psst, this issue will be closed with a templated response if it isn't a documentation update request.

**Comment by symbolpunk** [comment]
Hi there! It looks like you submitted an update request template without filling in the details. I'm going to close this for now, but feel free to reopen if you have a specific update request.💙🧡
