### ISSUE TITLE
Docs update request: /node-running/running-an-archive-node

### ISSUE THREAD

**Issue by pyropy** [OffchainLabs/arbitrum-docs#213]
Source: https://developer.arbitrum.io/node-running/running-an-archive-node

Request: After reading the documentation I'm still not sure do I need to run both arbitrum classic and nitro node in order to have full archival node, or running just the nitro node would be enough? 

My usecase for full-node would be to replay all transactions from beginning of the chain and listen feed relay, indexing the transactions to the database.

**Comment by symbolpunk** [comment]
Thanks very much for submitting this @pyropy. Acknowledging receipt; intending to address as part of an upcoming content refresh.

[Internal task for tracking -> [Clarify node-running options and procedures](https://www.notion.so/arbitrum/Clarify-node-running-options-and-procedures-46057a389a3141aaa054ec37057484c8)]

**Comment by pyropy** [comment]
> Thanks very much for submitting this @pyropy. Acknowledging receipt; intending to address as part of an upcoming content refresh.
> 
> [Internal task for tracking -> [Clarify node-running options and procedures](https://www.notion.so/arbitrum/Clarify-node-running-options-and-procedures-46057a389a3141aaa054ec37057484c8)]

Thank you @symbolpunk for response. Keep us posted about task progress as it's not public.

**Comment by symbolpunk** [comment]
No problem @pyropy - [here's a preview of the vNext document](https://nitro-docs-git-213-docs-edit-offchain-labs.vercel.app/node-running/running-an-archive-node) that @Jason-Wanxt has put together; does this meet your needs?

**Comment by pyropy** [comment]
@symbolpunk Thank you very much 🙏🏻
