### ISSUE TITLE
Security Concern for Breach,  I'm interested in assistance in receiving knowledge about my crypto conversion process that occurred in April of 2022

~● Please Advise if able ●~

### ISSUE THREAD

**Issue by tiffanyhowser** [OffchainLabs/arbitrum-docs#221]
https://github.com/Blockchair/Blockchair.Support/commit/d0400a60be4493606c7d031b97be3330e1

**Comment by TucksonDev** [comment]
Hello! This is the repository of the Arbitrum documentation. If you need assistance while using the Arbitrum ecosystem, please use [this form](https://support.arbitrum.io/hc/en-us/requests/new) or join our [Discord](https://discord.com/invite/arbitrum).
I'm going to close this for now, but feel free to reopen if you have a specific update request.💙🧡
