### ISSUE TITLE
do u offer using Binaries to run node?Docs about /node-running/build-nitro-locally

### ISSUE THREAD

**Issue by zekehao** [OffchainLabs/arbitrum-docs#226]
Source: https://developer.arbitrum.io/node-running/build-nitro-locally

Request: do u offer using Binaries to run node?

I represent an organization that requires us to run nodes using binaries rather than Docker. I noticed that your current offering only includes Docker-based nodes. Is it possible for us to obtain a binary-based node to meet our requirements?

If this is possible, please let me know the steps we should follow to obtain and run a binary-based node.

Thank you for your attention to this matter.

Best regards,

**Comment by mahsamoosavi** [comment]
Hi @zekehao! We don't provide binaries, but we have instructions on how to compile the node locally: https://developer.arbitrum.io/node-running/how-tos/build-nitro-locally

You can try that and reach us in our [Discord](https://discord.gg/ZpZuw7p) if you've got any question!

**Comment by chrisco512** [comment]
Also @zekehao it's recommended you use a Debian based Linux environment if you're building from source. Ubuntu or otherwise should work fine.
