### ISSUE TITLE
Docs update request: /chain-launching/quickstart-launch-l3-chain

### ISSUE THREAD

**Issue by crazyrabbitLTC** [OffchainLabs/arbitrum-docs#231]
Source: https://developer.arbitrum.io/chain-launching/quickstart-launch-l3-chain

Request: (how can we help?)

Psst, this issue will be closed with a templated response if it isn't a documentation update request.

Hello! It would be great to see this documentation!

**Comment by aroralanuk** [comment]
+1

Also, it will be helpful to have a guide to add custom precompiles for our rollup.

**Comment by symbolpunk** [comment]
Hey there Dennison - this issue is addressed by https://github.com/OffchainLabs/arbitrum-docs/pull/256.

@aroralanuk, please feel free to create a separate issue for your request and we'll triage it!
