### ISSUE TITLE
Docs update request: /node-running/gentle-introduction-run-node

### ISSUE THREAD

**Issue by nicovrg** [OffchainLabs/arbitrum-docs#245]
Source: https://developer.arbitrum.io/node-running/gentle-introduction-run-node

Request: If that page of the doc isn't written you could eventually link to an introduction, it was most likely written somewhere already in a blog post or in a twitter thread

**Comment by mahsamoosavi** [comment]
Thanks very much for submitting this @nicovrg . Acknowledging receipt; intending to address as part of an upcoming content refresh.

[Internal task for tracking -> [Author Gentle Introduction: Run a node](https://www.notion.so/arbitrum/Mahsa-Moosavi-25a672a538ea436b8b558c986c7c9e66?p=cb045b6b10a3473c8af1abd9cb933d07&pm=s)]
