### ISSUE TITLE
Docs update request: /arbos/l2-to-l1-messaging

### ISSUE THREAD

**Issue by DOBEN** [OffchainLabs/arbitrum-docs#282]
Source: https://developer.arbitrum.io/arbos/l2-to-l1-messaging

Suggestion: could there be a link to what an `RBlock` is in `and consequently, part of what's asserted in every RBlock`, please?
 
Initially, though it is a typo and should be `Block`.

**Comment by mahsamoosavi** [comment]
Hi there! Thanks for submitting the issue!

`RBlock` is an assertion by an Arbitrum validator that represents a claim about an Arbitrum chain's state. 
We provide detailed description of Arbitrum terms in [Arbitrum glossary](https://developer.arbitrum.io/intro/glossary).

I'm going to close this, but feel free to reopen if you have a specific update request.💙🧡
