### ISSUE TITLE
Docs update request: /node-running/node-providers

### ISSUE THREAD

**Issue by deverka** [OffchainLabs/arbitrum-docs#285]
Source: https://developer.arbitrum.io/node-running/node-providers

Request: (how can we help?)

Can you please add OnFinality as one of the node providers for Arbitrum (Arb One). 
See more details here: https://onfinality.io/networks/arbitrum

We'd appreciate this very much.

**Comment by mahsamoosavi** [comment]
> Source: https://developer.arbitrum.io/node-running/node-providers
> 
> Request: (how can we help?)
> 
> Can you please add OnFinality as one of the node providers for Arbitrum (Arb One). See more details here: https://onfinality.io/networks/arbitrum
> 
> We'd appreciate this very much.

Hi there! Thanks for submitting the issue! 

We have a new process for listing node providers in the documentation.

Please, submit a request via [this form](https://docs.google.com/forms/d/e/1FAIpQLSezhBlPgKIKKWgXKUz4MmlJPdHyfmPQlxUtS48HlRoi0e14_Q/viewform) and, upon acceptance, OnFinality will be listed both in [the portal](https://portal.arbitrum.one/#nodeproviders) and in this page.
Thanks!
