### ISSUE TITLE
[Docs] Add dStorage section on dev's guide

### ISSUE THREAD

**Issue by badkk** [OffchainLabs/arbitrum-docs#32]
**Is your feature request related to a problem? Please describe.**
There's no section about dStorage description, like https://ethereum.org/en/developers/docs/storage/

**Describe the solution you'd like**
Add dStorage under devs' wiki page

**Comment by DZGoldman** [comment]
This topic isn't particularly relevant to Arbitrum; if we expand to include more general web3 docs, will revisit
