### ISSUE TITLE
Docs update request: /node-running/node-providers

### ISSUE THREAD

**Issue by lucyxliu** [OffchainLabs/arbitrum-docs#340]
Source: https://developer.arbitrum.io/node-running/node-providers

Request: adding 1RPC as a node provider
We currently support Arbitrum One endpoint (https://1rpc.io/arb), and have relayed over 1.2 billion requests, averaging on 15 million requests per day.

https://docs.ata.network/1rpc/introduction/

**Comment by TucksonDev** [comment]
Hello! Thanks for submitting the issue.

We have a new process for listing node providers in the documentation.

Please, submit a request via [this form](https://docs.google.com/forms/d/e/1FAIpQLSezhBlPgKIKKWgXKUz4MmlJPdHyfmPQlxUtS48HlRoi0e14_Q/viewform) and, upon acceptance, the provider will be listed both in [the portal](https://portal.arbitrum.one/#nodeproviders) and in this page.
Thanks!

**Comment by lucyxliu** [comment]
Hi, we have successfully submitted 1RPC in the Portal before and it's listed already 
https://portal.arbitrum.io/one?categories=rpc#nodeproviders

It would be great if you could also update the documentation!

**Comment by TucksonDev** [comment]
1RPC has been added to the list of providers.
Thanks!
