### ISSUE TITLE
Docs update request: /node-running/node-providers

### ISSUE THREAD

**Issue by Mummyhap** [OffchainLabs/arbitrum-docs#346]
Source: https://developer.arbitrum.io/node-running/node-providers

BlockPI has successfully launched RPC service for Arbitrum Nova.  Please give a "check" in the Arb Nova for BlockPI.

public: https://arbitrum-nova.blockpi.network/v1/rpc/public
Chainlist: https://chainlist.org/chain/42170
dashboard: https://dashboard.blockpi.io/workbench/dashboard

**Comment by TucksonDev** [comment]
Nova has been added for BlockPi. Thanks!
