### ISSUE TITLE
Docs update request: /proving/challenge-manager

### ISSUE THREAD

**Issue by doanchuong** [OffchainLabs/arbitrum-docs#352]
Source: https://developer.arbitrum.io/proving/challenge-manager

Request: (how can we help?)

Psst, this issue will be closed with a templated response if it isn't a documentation update request.
```[tasklist]
### Tasks
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/314
- [ ] https://github.com/OffchainLabs/arbitrum-docs/issues/349
```

**Comment by TucksonDev** [comment]
Hi there! It looks like you submitted an update request template without filling in the details. I'm going to close this for now, but feel free to reopen if you have a specific update request.💙🧡
