### ISSUE TITLE
Lowercase precompile method names in docs

### ISSUE THREAD

**Issue by fionnachan** [OffchainLabs/arbitrum-docs#37]
They’re uppercased for the purpose of Go exporting functions for our ABI binding, but they’re actually lowercase as users access them from solidity. This applies both to the “common precompiles” and “full precompiles” documents.

_original ticket created by @PlasmaPower on 6 Dec 2022_

**Comment by thearyanag** [comment]
Hey , can someone assing this issue to me. ?

**Comment by thearyanag** [comment]
Hey @DZGoldman please check and let me know if any changes needed.

**Comment by DZGoldman** [comment]
https://github.com/OffchainLabs/arbitrum-docs/pull/49
