### ISSUE TITLE
I have signed CLA but sill shows check as "errror" on pull request

### ISSUE THREAD

**Issue by daizhengxue** [OffchainLabs/arbitrum-docs#401]
URL to the linked https://github.com/OffchainLabs/arbitrum-docs/pull/400

I double checked at our export list and can confirm that I has signed the CLA, but the check is still "errored" on the pull request.

**Comment by TucksonDev** [comment]
Hey @daizhengxue !
The bot requires a manual confirmation after signing the CLA. I saw my colleague already added you to the list and that check is passed.
I'll close this issue now and will reply to your PR too.
