### ISSUE TITLE
mdx dream: tooltip to show word definition from glossary on hover 

### ISSUE THREAD

**Issue by DZGoldman** [OffchainLabs/arbitrum-docs#42]
Something like: keep a js mapping of word-id to definition; can wrap any text in a component that inputs an id and tooltips the definition (glossary page will use the same mapping to render the text directly)

**Comment by DZGoldman** [comment]
@fionnachan it wasn't mine (but I forget whose it was)

**Comment by symbolpunk** [comment]
[#112](https://github.com/OffchainLabs/arbitrum-docs/pull/112) closes this 🤙

**Comment by symbolpunk** [comment]
(jk I pasted the wrong PR, but this is implemented)

**Comment by DZGoldman** [comment]
(🔜 )

**Comment by symbolpunk** [comment]
Todo: use `notion-docs-generator` to pull & inject definitions within `notion-docs/scripts/update.ts` (like staged implementation 🙏)
