### ISSUE TITLE
Docs update request: /for-devs/dev-tools-and-resources/web3-libraries-tools

### ISSUE THREAD

**Issue by wdcollier** [OffchainLabs/arbitrum-docs#426]
Source: https://developer.arbitrum.io/for-devs/dev-tools-and-resources/web3-libraries-tools

Request: Add the following paragraph about The Box at the bottom of Dev Tools & Resources page:

**The Box by Decent.xyz**
[[The Box](https://docs.decent.xyz/docs/overview)](https://docs.decent.xyz/docs/overview) enables 1-click transactions using any token on any chain + on-ramping from fiat to any token on any chain. For NFT marketplaces or applications, The Box enables checkout for any NFT, with any token, across chains and primary and secondary sales. The Box meets collectors at their point of liquidity, enabling them to spend tokens seamlessly across chains. Developers can implement The Box by easily importing just one React component or using APIs.

Psst, this issue will be closed with a templated response if it isn't a documentation update request.

**Comment by anegg0** [comment]
Stale issue: the project's URL lands a 404.
