### ISSUE TITLE
Revera

### ISSUE THREAD

**Issue by mehong07** [OffchainLabs/arbitrum-docs#440]
REVERA this testnet becomes an important place as a place to learn protocols properly and perfectly. Thank you for giving us an opportunity that we may not get back as testers. As a tester, I am quite satisfied and believe that this project can develop even better later after the team has received all input from the community! the important thing for a project is to be able to receive input from the community! success always for the team.

**Comment by TucksonDev** [comment]
Hello!
It looks like you might have added an issue that is not related to the Developer Docs portal of Arbitrum. I'm going to close this for now, but feel free to reopen and add more details about the issue you're encountering, or the content you'd like to see in the portal.
