### ISSUE TITLE
Revera

### ISSUE THREAD

**Issue by mehong07** [OffchainLabs/arbitrum-docs#441]
Revera This project is really great, the features are interesting and there are some things that make me really like it, namely: 1. the transaction is fast 2. Elegant and easy to use 3. the user can understand the menu perfectly 4. There are no defects in the design 5. the product runs according to what the user expects always success and hopefully it can be a promising project when mainnet arrives.

**Comment by TucksonDev** [comment]
Hello!
It looks like you might have added an issue that is not related to the Developer Docs portal of Arbitrum. I'm going to close this for now, but feel free to reopen and add more details about the issue you're encountering, or the content you'd like to see in the portal.
