### ISSUE TITLE
Docs update request: /arbos/l1-pricing

### ISSUE THREAD

**Issue by Cristianoluizz** [OffchainLabs/arbitrum-docs#470]
Source: https://docs.arbitrum.io/arbos/l1-pricing

Request: (how can we help?)

Psst, this issue will be closed with a templated response if it isn't a documentation update request.
```[tasklist]
### Tasks
```

**Comment by TucksonDev** [comment]
Hi there! It looks like you submitted an update request template without filling in the details. I'm going to close this for now, but feel free to reopen if you have a specific update request.💙🧡
