### ISSUE TITLE
Docs update request: /arbos/gas

### ISSUE THREAD

**Issue by mail731212** [OffchainLabs/arbitrum-docs#511]
Source: https://docs.arbitrum.io/arbos/gas

Request: (how can we help?)

Psst, this issue will be closed with a templated response if it isn't a documentation update request.

**Comment by symbolpunk** [comment]
Hi there! It looks like you submitted an update request template without filling in the details. I'm going to close this for now, but feel free to reopen if you have a specific update request.💙🧡
