### ISSUE TITLE
Docs update request: /getting-started-devs

### ISSUE THREAD

**Issue by crokau** [OffchainLabs/arbitrum-docs#565]
Source: https://docs.arbitrum.io/getting-started-devs

Request: Add SmartPress as a contract creator option

You should add Smartpress as a simple option to create smart contracts. 

Its by far the easiest tool to get started with a testnet MVP of any idea.

Polygon added it a few weeks ago.

https://wiki.polygon.technology/docs/pos/deploy/smartpress/

Smartpress.ai is the link.

It's free. 

Builds, debugs, compiles and deploys to arbitrum.

**Comment by symbolpunk** [comment]
Thanks for this! We generally include links to other products in our docs only when those products are either partner products or widely adopted by our dev community. Closing as ineligible, but don't hesitate to comment if this is an error.
