### ISSUE TITLE
Docs update request: /stylus/reference/opcode-hostio-pricing

### ISSUE THREAD

**Issue by 1KitCat1** [OffchainLabs/arbitrum-docs#575]
Source: https://docs.arbitrum.io/stylus/reference/opcode-hostio-pricing

Request: In write_result I think there should be 1.2513 in the GAS column, not 12513

**Comment by symbolpunk** [comment]
TY! https://github.com/OffchainLabs/arbitrum-docs/pull/672 fixes.
