### ISSUE TITLE
Docs update request: /devs-how-tos/how-to-use-oracles

### ISSUE THREAD

**Issue by Dillon-DIA** [OffchainLabs/arbitrum-docs#719]
Source: https://docs.arbitrum.io/devs-how-tos/how-to-use-oracles

Request: Hello Arbitrum team! I've proposed the following changes to this page via PR: https://github.com/OffchainLabs/arbitrum-docs/compare/master...Dillon-DIA:arbitrum-docs:patch-2?diff=unified

I've also proposed an update to the page: arbitrum-docs/for-devs/dev-tools-and-resources/oracles.mdx, which can be accessed here: https://github.com/OffchainLabs/arbitrum-docs/compare/master...Dillon-DIA:arbitrum-docs:patch-1

Thank you!

**Comment by pete-vielhaber** [comment]
Will add via [PR 1917](https://github.com/OffchainLabs/arbitrum-docs/pull/1917), due to changes in the structure of the docs from the receipt of this issue to completion.

**Comment by pete-vielhaber** [comment]
Merged
