### ISSUE TITLE
Docs update request: /launch-orbit-chain/orbit-quickstart

### ISSUE THREAD

**Issue by yigityektin** [OffchainLabs/arbitrum-docs#786]
Source: https://docs.arbitrum.io/launch-orbit-chain/orbit-quickstart

Request: (how can we help?)
In the docs, you said that 1 testnet ETH will be needed but in the Orbit chain deployment UI it says that 1.5 testnet ETH will be needed.
Docs:
![image](https://github.com/OffchainLabs/arbitrum-docs/assets/87423873/4eb77e65-a493-4994-8373-3c708df41cfd)
Orbit Chain Deployment UI:
![image](https://github.com/OffchainLabs/arbitrum-docs/assets/87423873/fc16e82d-09ec-4bcd-b792-a4dab76a50e1)

**Comment by anegg0** [comment]
@yigityektin , thank you for your suggestion. We have made the adjustments.
