### ISSUE TITLE
Docs update request: /for-devs/concepts/precompiles

### ISSUE THREAD

**Issue by lj92458** [OffchainLabs/arbitrum-docs#792]
Source: https://docs.arbitrum.io/for-devs/concepts/precompiles

Request: 

Please explain the data structure of the ticket. And why ticket cannot be forged or tampered. or fabricated out of thin air

**Comment by TucksonDev** [comment]
Hey @lj92458 !
Can you explain a bit further what changes you'd like to see in that page? Maybe mention any new sections you'd like to see, or what information you'd edit.
Thanks.
