### ISSUE TITLE
Docs update request: /arbos/l1-to-l2-messaging

### ISSUE THREAD

**Issue by lj92458** [OffchainLabs/arbitrum-docs#793]
Source: https://docs.arbitrum.io/arbos/l1-to-l2-messaging

Request: (how can we help?)

Can I forge message? If I don't send coin to the L1 router, then I forge a ticket and manually call redemption, who can detect and stop me?
Who has the authority to call the inboxContract to create a ticket?  Is inboxContract decentralized? Who can supervise these callers?

**Comment by TucksonDev** [comment]
Hey @lj92458 , this repository handles issues related to the documentation portal. 
For inquiries about the protocol in general and how it works, you can ask in our [Discord server](https://discord.gg/arbitrum). We have a specific channel for protocol-related questions (called #protocol).
Thanks!
