### ISSUE TITLE
Docs update request: /arbos/l1-to-l2-messaging

### ISSUE THREAD

**Issue by lj92458** [OffchainLabs/arbitrum-docs#794]
Source: https://docs.arbitrum.io/arbos/l1-to-l2-messaging

Is the bridge decentralised ？ every body can run the bridge app?

**Comment by TucksonDev** [comment]
Hey @lj92458 , this repository handles issues related to the documentation portal. 
For inquiries about the protocol in general and how it works, you can ask in our [Discord server](https://discord.gg/arbitrum). We have a specific channel for protocol-related questions (called #protocol).
Thanks!
