### ISSUE TITLE
Docs update request: /for-devs/third-party-docs/Supra/use-supras-price-feed-oracle

### ISSUE THREAD

**Issue by ksdumont** [OffchainLabs/arbitrum-docs#825]
Source: https://docs.arbitrum.io/for-devs/third-party-docs/Supra/use-supras-price-feed-oracle

Request: We just deployed our Pull model to arbitrum, can we update and add this blurb right before 'To see all of the networks Supra is on, please visit [Supras' Networks](https://supraoracles.com/docs/price-feeds/networks)!': 

'Supra provides decentralized oracle price feeds that can be used for on-chain and off-chain use-cases such as spot and perpetual DEXes, lending protocols, and payments protocols. Supra’s oracle chain and consensus algorithm makes it the fastest-to-finality oracle provider, with layer-1 security guarantees. The pull oracle has a sub-second response time. Aside from speed and security, Supra’s rotating node architecture gathers data from 40+ data sources and applies a robust calculation methodology to get the most accurate value. The node provenance on the data dashboard also provides a fully transparent historical audit trail. Supra’s Distributed Oracle Agreement (DORA) paper was accepted into ICDCS 2023, oldest distributed systems conference.'

Thank you in advance for your help. Kindly let me know if you need any additional information.

Best, 
Keith

**Comment by mahsamoosavi** [comment]
> Source: https://docs.arbitrum.io/for-devs/third-party-docs/Supra/use-supras-price-feed-oracle
> 
> Request: We just deployed our Pull model to arbitrum, can we update and add this blurb right before 'To see all of the networks Supra is on, please visit [Supras' Networks](https://supraoracles.com/docs/price-feeds/networks)!':
> 
> 'Supra provides decentralized oracle price feeds that can be used for on-chain and off-chain use-cases such as spot and perpetual DEXes, lending protocols, and payments protocols. Supra’s oracle chain and consensus algorithm makes it the fastest-to-finality oracle provider, with layer-1 security guarantees. The pull oracle has a sub-second response time. Aside from speed and security, Supra’s rotating node architecture gathers data from 40+ data sources and applies a robust calculation methodology to get the most accurate value. The node provenance on the data dashboard also provides a fully transparent historical audit trail. Supra’s Distributed Oracle Agreement (DORA) paper was accepted into ICDCS 2023, oldest distributed systems conference.'
> 
> Thank you in advance for your help. Kindly let me know if you need any additional information.
> 
> Best, Keith

Hey @ksdumont - I'd propose maintaining an objective, neutral tone that aligns with established conventions in our devdocs. Some of our docs have marketing/promotional language, but it's something we aim to reduce over time.

In this case, a section within this page that focuses primarily on "`what it is`" and "`how to use it`" (`vs "why you should use it`") could work well.

Feel free to issue PRs directly into your document, as the [designated maintainer](https://docs.arbitrum.io/for-devs/third-party-docs/contribute) of the content. 

Thank you! 💙

**Comment by ksdumont** [comment]
Hi, I am just stating the facts about our tech here. What exactly do you want edited? Could you merge this PR?
