### ISSUE TITLE
Docs update request: /intro

### ISSUE THREAD

**Issue by HUANGJIEis** [OffchainLabs/arbitrum-docs#876]
Source: https://docs.arbitrum.io/intro

Request: (how can we help?)

Psst, this issue will be closed with a templated response if it isn't a documentation update request.
```[tasklist]
### Tasks
```

**Comment by TucksonDev** [comment]
Hi there! It looks like you submitted an update request template without filling in the details. I'm going to close this for now, but feel free to reopen if you have a specific update request.💙🧡

**Comment by HUANGJIEis** [comment]
我想学，怎么控制别人钱包



---Original---
From: ***@***.***&gt;
Date: Tue, Jan 16, 2024 16:53 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [OffchainLabs/arbitrum-docs] Docs update request: /intro (Issue#876)




 
Closed #876 as not planned.
