### ISSUE TITLE
Docs update request: /node-running/how-tos/running-an-orbit-node

### ISSUE THREAD

**Issue by medardm** [OffchainLabs/arbitrum-docs#910]
Source: https://docs.arbitrum.io/node-running/how-tos/running-an-orbit-node

Request: I think it would be great if there was also a video tutorial to make setting up an orbit node easier for total beginners.

Psst, this issue will be closed with a templated response if it isn't a documentation update request.
```[tasklist]
### Tasks
```

**Comment by anegg0** [comment]
Thank you for your suggestion, duly noted, and sorry for the delayed response, @medardm!
