### ISSUE TITLE
**Describe the bug**

### ISSUE THREAD

**Issue by Mikegoossens1980** [OffchainLabs/arbitrum-docs#930]
**Describe the bug**
`@walletconnect/ethereum-provider` currently depends on `@web3modal/standalone`. Web3Modal, however, behaves as a singleton. If different versions are resolved in an application, this can cause subtle issues.

Should `@web3modal/standalone` be moved to the `peerDependencies` of `@walletconnect/ethereum-provider`?

I also note that Web3Modal has released breaking changes on minor version bumps. Does the dependency version need to be specified more precisely? 

_Originally posted by @nhardy in https://github.com/WalletConnect/walletconnect-monorepo/issues/2102_

_Originally posted by @Mikegoossens1980 in https://github.com/Mikegoossens1980/musical-octo-guide/issues/1_

**Comment by TucksonDev** [comment]
Hey, it looks like this issue doesn't relate to the Arbitrum documentation portal. I'll close the ticket for now, but feel free to reopen and add more context to it.
Thanks!
